apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbazaar-kibana
  namespace: bbazaar-prod-in
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbazaar-kibana
  template:
    metadata:
      labels:
        app: bbazaar-kibana
    spec:
      containers:
        - name: bbazaar-kibana
          image: docker.elastic.co/kibana/kibana:8.11.0
          resources:
            limits:
              memory: "1Gi"
              cpu: "1500m"
            requests:
              cpu: 250m
              memory: 1Gi
          ports:
            - name: bbazaar-kibana
              containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              # http://<service-name>.<namespace>.svc.cluster.local:<port-number>
              value: http://bbazaar-elastic.bbazaar-prod-in.svc.cluster.local:9200
            - name: ELASTICSEARCH_USERNAME
              value: kibana_system
            - name: ELASTICSEARCH_PASSWORD
              # add to secret file
              value: kibana
            - name: ELASTICSEARCH_SERVICEACCOUNT_TOKEN
              value: AAEAAWVsYXN0aWMva2liYW5hL2pvYmJlci1raWJhbmE6TnFCQ09yMW5TSldtUjlHR1JSaXNGUQ
          volumeMounts:
            - name: kibana-config
              mountPath: /usr/share/kibana/config
      volumes:
        - name: kibana-config
          configMap:
            name: kibana-config
