apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbazaar-notification
  namespace: bbazaar-prod-in
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbazaar-notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: bbazaar-notification
    spec:
      containers:
        - name: bbazaar-notification
          image: prabhasranjan0/bbazaar-notification:stable
          imagePullPolicy: Always
          resources:
            # limits:
            #   cpu: "0.5"
            #   memory: 1Gi
            # requests:
            #   cpu: 100m
            #   memory: 150Mi
          ports:
            - name: notification
              containerPort: 4001
          env:
            - name: ENABLE_APM
              value: "1"
            - name: NODE_ENV
              value: "production"
            - name: CLIENT_URL
              value: "https://bbazaar.com"
            - name: RABBITMQ_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: bbazaar-backend-secret
                  key: bbazaar-rabbitmq-endpoint
            - name: SENDER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: bbazaar-backend-secret
                  key: sender-email
            - name: SENDER_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bbazaar-backend-secret
                  key: sender-email-password
            - name: ELASTIC_SEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: bbazaar-backend-secret
                  key: bbazaar-elasticsearch-url
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: bbazaar-backend-secret
                  key: bbazaar-elastic-apm-server-url
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bbazaar-backend-secret
                  key: bbazaar-elastic-apm-secret-token
