apiVersion: v1
kind: Service
metadata:
  name: bbazaar-elastic
  namespace: bbazaar-prod-in
spec:
  type: ClusterIP
  selector:
    app: bbazaar-elastic
  ports:
    - name: rest
      port: 9200
      targetPort: 9200
      protocol: TCP
    - name: inter-node
      port: 9300
      targetPort: 9300
      protocol: TCP
