apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: bbazaar-prod-in
spec:
  storageClassName: postgres-local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/postgresql/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: bbazaar-prod-in
spec:
  storageClassName: postgres-local-storage
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
