apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: bbazaar-prod-in
spec:
  storageClassName: redis-local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data1"
