apiVersion: v1
kind: Service
metadata:
  name: jobber-auth
  namespace: bb-prod
spec:
  type: ClusterIP
  selector:
    app: jobber-auth
  ports:
    - name: auth
      port: 4002
      targetPort: 4002
      protocol: TCP
