apiVersion: v1
kind: Service
metadata:
  name: bbazaar-users
  namespace: bbazaar-prod-in
spec:
  type: ClusterIP
  selector:
    app: bbazaar-users
  ports:
    - name: users
      port: 4003
      targetPort: 4003
      protocol: TCP
