apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: bb-prod
spec:
  storageClassName: mysql-local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: bb-prod
spec:
  storageClassName: mysql-local-storage
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
