# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: bbazaar-mongo
#   namespace: bbazaar-prod-in
# spec:
#   selector:
#     matchLabels:
#       app: bbazaar-mongo
#   serviceName: bbazaar-mongo
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: bbazaar-mongo
#     spec:
#       containers:
#       - name: bbazaar-mongo
#         image: mongo:latest
#         ports:
#         - containerPort: 27017
#           name: bbazaar-mongo
#         volumeMounts:
#         - name: mongo-local-storage
#           mountPath: /data/db
#       volumes:
#       - name: mongo-local-storage
#         persistentVolumeClaim:
#           claimName: mongo-pvc

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bbazaar-mongo
  namespace: bbazaar-prod-in
spec:
  selector:
    matchLabels:
      app: bbazaar-mongo
  serviceName: bbazaar-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: bbazaar-mongo
    spec:
      containers:
        - name: bbazaar-mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
              name: bbazaar-mongo
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          hostPath:
            path: /mnt/data/mongo
            type: DirectoryOrCreate
