apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
  namespace: bb-prod
spec:
  storageClassName: elasticsearch-local-storage
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: bb-prod
spec:
  storageClassName: elasticsearch-local-storage
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
