apiVersion: v1
kind: Service
metadata:
  name: jobber-elastic
  namespace: bb-prod
spec:
  type: ClusterIP
  selector:
    app: jobber-elastic
  ports:
    - name: rest
      port: 9200
      targetPort: 9200
      protocol: TCP
    - name: inter-node
      port: 9300
      targetPort: 9300
      protocol: TCP
