apiVersion: v1
kind: Service
metadata:
  name: bbazaar-queue
  namespace: bbazaar-prod-in
spec:
  type: ClusterIP
  selector:
    app: bbazaar-queue
  ports:
    - name: queue
      port: 5672
      targetPort: queue
      protocol: TCP
    - name: mgmt
      port: 15672
      targetPort: mgmt
      protocol: TCP
