apiVersion: v1
kind: Service
metadata:
  name: jobber-notification
  namespace: bb-prod
spec:
  type: ClusterIP
  selector:
    app: jobber-notification
  ports:
    - name: notification
      port: 4001
      targetPort: 4001
      protocol: TCP
